name: 2DevsEquipmentEffects
version: ${project.version}
main: com.ignitedev.devsequipmenteffects.EquipmentEffects
api-version: 1.13
authors: [ IgniteDEV, 2DevsStudio ]
description: Equipment effects plugin by 2DevsStudio
commands:
  equipmenteffectsadmin:
    aliases: [ eea, equipmenteffectsa, equipmentea, eeffectsadmin, eeadmin ]
    description: admin command