name: 2DevsEquipmentEffects
version: ${project.version}
main: com.ignitedev.devsequipmenteffects.EquipmentEffects
api-version: 1.16
authors: [ IgniteDEV, 2DevsStudio ]
description: Equipment effects plugin by 2DevsStudio
