# that's  default itemstack, if you want to create another,
# just create new file with own name, you need .yml as extension ;)


# id to identify item (for example in give command)
id: "DEFAULT"

# name of item
name: "Default item"

# [!] Information
# options: must-wear | must-hold-mainhand | must-hold-offhand can be used together at the same time :)

# if true, player have to wear that item to make it work, hands does not count
must-wear: true

# if both {must-hold-mainhand} and {must-hold-offhand} that makes it work for both hands

# if true, player have to hold item in main hand to make it work
must-hold-mainhand: false

# if true, player have to hold item in off hand to make it work
must-hold-offhand: false

# effects which will be applied
# format: EFFECT:AMPLIFIER
# EFFECTS: (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html)
applicable-effects:
  - "SPEED:2"

# section for interactions on triggering with {must-wear} or {must-hold-mainhand} or {must-hold-offhand}
trigger-interactions:

  # placeholders:
  # %player% -> Nickname of executing player

  # trigger on triggering enable for interaction ( example; holding item )
  trigger-enable:

    # command which will be executed
    command:
      - "say Trigger on for %player%"
      - "say Test123"

  # trigger on triggering disable for interaction ( example; un-holding item )
  trigger-disable:

    # command which will be executed
    command:
      - "say Trigger off"
      - "say Test123"


# itemstack for which effects will work(it don't have to be given by command, just similar itemstack
# for more information about how this section work, go here: https://www.spigotmc.org/wiki/itemstack-serialization/
itemstack:
  ==: org.bukkit.inventory.ItemStack
  v: 2230
  type: IRON_BOOTS
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: "Default Item"